version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    volumes:
      - ./front:/go/src/github.com/originbenntou/E-Kitchen/front
      - ./front/template:/template
    ports:
      - "80:8080"
