version: '3'
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ../:/usr/share/nginx/html
        links:
            - php
    php:
        image: "php:7.2-fpm"
        ports:
            - "9000:9000"
        volumes:
            - ../:/code
